Task 2
Pavel545/let-s-play-cards pull request #2
Opened 2022-08-02 13:22 UTC by Pavel545

Исправлены ранее указанные недочёты.

2022-08-03 06:47 UTC, mrerberg requested changes

2022-08-03 06:47 UTC, mrerberg commented on index.html
> +    <script>
Почему в теге скриптс, если остальной код в файлах?

2022-08-03 06:47 UTC, mrerberg commented on index.html
> +    <script src="src\js\block_layout.js"></script>
Ты какие в итоге слеши используешь?

2022-08-03 06:47 UTC, mrerberg commented on src/js/game_process.js
> +function game() {
Я бы подобрал более подходящее название, более описательное для данной функции

2022-08-03 10:37 UTC, Pavel545 commented on index.html
> +    <script>
ну да как и  указанно эта строка была удалена в этом пулле потому что я всё раскидал по другим файлам

2022-08-04 06:33 UTC, mrerberg requested changes

2022-08-04 06:33 UTC, mrerberg commented on index.html
> +    <script>
В данном пуллреквесте показано, что состояние инициализируется в script теге, а не в отдельном файле

2022-08-04 06:33 UTC, mrerberg commented on src/js/block_layout.js
> +    window.application.renderBlock("example-false" ,complexity_choice_area, 'complexity_choice_button','1','easy');
Очень много аргументов принимает данная функция и неочевидно, что каждый значит. ПРедлагаю так

```js
renderBlock({
  classes: ['complexity_choice_button'],
  content: "1",
  dataAttrs: ['easy'],
})
```

2022-08-04 06:33 UTC, mrerberg commented on src/js/game_process.js
> +function beginningGame() {
Функции принято все же именовать с глагола. startGame?

2022-08-04 09:54 UTC, Pavel545 commented on src/js/block_layout.js
> +    window.application.renderBlock("example-false" ,complexity_choice_area, 'complexity_choice_button','1','easy');
я конечно попытался, но что-то ошибок повылазило сразу отовсюду типа:
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('[object Object]') contains HTML space characters, which are not valid in tokens.
притом что до этого такого не было и всё коректно работало только вот с таким пояснение что то начинает ему не нравится и я чёт не пойму почему

2022-08-05 06:29 UTC, mrerberg commented on src/js/block_layout.js
> +    window.application.renderBlock("example-false" ,complexity_choice_area, 'complexity_choice_button','1','easy');
А ты подготовил саму функцию к тому, что она теперь принимает один аргумент-объект?  Когда декларируешь функцию?

Было
function someFn(a, b, c, d) {}

Стало
function someFn({ a, b, c, d }) {}

2022-08-06 05:55 UTC, merged